### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [Zooloth/prj-rev-bwfs-dasmoto#5]
**GRADE**: Needs Improvement

**SUMMARY**: Great start on this project. The site looks great and you did an excellent job keeping the project folder organized using a separate folder for your resources. Good idea to include divs to help structure your code as well!

Behind the scenes, try to always keep in mind DRY principles. Avoid setting the same styling many times for similarly styled elements wherever possible. Also, consider using html entities to represent the special characters to ensure that they display correctly across all browsers.

As a next step try saving your image files locally to an images folder inside of resources and then use relative file paths to link to those from your html and css. The link to css on line 4 of your html is a great example and more info can be found [here](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/).

Have fun and keep up the good work!

**Comment by Zooloth** [comment]
Thank you for looking over my code and giving me the great feedback. I had totally forgotten about using entities and will make sure to do so from now on. I will also start to keep my image files locally in a folder. I will also try to use the DRY principles more in my future projects.
